package de.SlamWeasel.SurvivalHelper.util;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.inventory.meta.SpawnEggMeta;

public class NameFix
{
    private static String name;
    private static int sub;

    public static String getName(ItemStack i)
    {
        switch (i.getType().toString())
        {
            case "ACACIA_DOOR_ITEM"             :name = "Acacia Door";
                                                 break;
            case "ACACIA_FENCE"                 :name = "Acacia Fence";
                                                 break;
            case "ACACIA_FENCE_GATE"            :name = "Acacia Fence Gate";
                                                 break;
            case "ACACIA_STAIRS"                :name = "Acacia Wood Stairs";
                                                 break;
            case "ACTIVATOR_RAIL"               :name = "Activator Rail";
                                                 break;
            case "ANVIL"                        :name = "Anvil";
                                                 break;
            case "APPLE"                        :name = "Apple";
                                                 break;
            case "ARMOR_STAND"                  :name = "Armor Stand";
                                                 break;
            case "ARROW"                        :name = "Arrow";
                                                 break;
            case "BAKED_POTATO"                 :name = "Baked Potato";
                                                 break;
            case "BANNER"                       :name = color(15 - i.getData().getData()) + " Banner";
                                                 break;
            case "BARRIER"                      :name = "Barrier";
                                                 break;
            case "BEACON"                       :name = "Beacon";
                                                 break;
            case "BED"                          :name = color(i.getData().getData()) + " Bed";
                                                 break;
            case "BEETROOT"                     :name = "Beetroot";
                                                 break;
            case "BEETROOT_SEEDS"               :name = "Beetroot Seeds";
                                                 break;
            case "BEETROOT_SOUP"                :name = "Beetroot Soup";
                                                 break;
            case "BIRCH_DOOR_ITEM"              :name = "Birch Door";
                                                 break;
            case "BIRCH_FENCE"                  :name = "Birch Fence";
                                                 break;
            case "BIRCH_FENCE_GATE"             :name = "Birch Fence Gate";
                                                 break;
            case "BIRCH_WOOD_STAIRS"            :name = "Birch Wood Stairs";
                                                 break;
            case "BLACK_GLAZED_TERRACOTTA"      :name = "Black Glazed Terracotta";
                                                 break;
            case "BLACK_SHULKER_BOX"            :name = "Black Shulker Box";
                                                 break;
            case "BLAZE_POWDER"                 :name = "Blaze Powder";
                                                 break;
            case "BLAZE_ROD"                    :name = "Blaze Rod";
                                                 break;
            case "BLUE_GLAZED_TERRACOTTA"       :name = "Blue Glazed Terracotta";
                                                 break;
            case "BLUE_SHULKER_BOX"             :name = "Blue Shulker Box";
                                                 break;
            case "BOAT"                         :name = "Oak Boat";
                                                 break;
            case "BOAT_ACACIA"                  :name = "Acacia Boat";
                                                 break;
            case "BOAT_BIRCH"                   :name = "Birch Boat";
                                                 break;
            case "BOAT_DARK_OAK"                :name = "Dark Oak Boat";
                                                 break;
            case "BOAT_JUNGLE"                  :name = "Jungle Boat";
                                                 break;
            case "BOAT_SPRUCE"                  :name = "Spruce Boat";
                                                 break;
            case "BONE"                         :name = "Bone";
                                                 break;
            case "BONE_BLOCK"                   :name = "Bone Block";
                                                 break;
            case "BOOK"                         :name = "Book";
                                                 break;
            case "BOOK_AND_QUILL"               :name = "Book and Quill";
                                                 break;
            case "BOOKSHELF"                    :name = "Bookshelf";
                                                 break;
            case "BOW"                          :name = "Bow";
                                                 break;
            case "BOWL"                         :name = "Bowl";
                                                 break;
            case "BREAD"                        :name = "Bread";
                                                 break;
            case "BREWING_STAND_ITEM"           :name = "Brewing Stand";
                                                 break;
            case "BRICK"                        :name = "Bricks";
                                                 break;
            case "BRICK_STAIRS"                 :name = "Brick Stairs";
                                                 break;
            case "BROWN_GLAZED_TERRACOTTA"      :name = "Brown Glazed Terracotta";
                                                 break;
            case "BROWN_MUSHROOM"               :name = "Mushroom";
                                                 break;
            case "BROWN_SHULKER_BOX"            :name = "Brown Shulker Box";
                                                 break;
            case "BUCKET"                       :name = "Bucket";
                                                 break;
            case "CACTUS"                       :name = "Cactus";
                                                 break;
            case "CAKE"                         :name = "Cake";
                                                 break;
            case "CARPET"                       :name = color(i.getData().getData()) + " Carpet";
                                                 break;
            case "CARROT_ITEM"                  :name = "Carrot";
                                                 break;
            case "CARROT_STICK"                 :name = "Carrot on a Stick";
                                                 break;
            case "CAULDRON_ITEM"                :name = "Cauldron";
                                                 break;
            case "CHEST"                        :name = "Chest";
                                                 break;
            case "CHORUS_FLOWER"                :name = "Chorus Flower";
                                                 break;
            case "CHORUS_FRUIT"                 :name = "Chorus Fruit";
                                                 break;
            case "CHORUS_FRUIT_POPPED"          :name = "Popped Chorus Fruit";
                                                 break;
            case "CHORUS_PLANT"                 :name = "Chorus Plant";
                                                 break;
            case "CLAY"                         :name = "Clay";
                                                 break;
            case "CLAY_BALL"                    :name = "Clay";
                                                 break;
            case "CLAY_BRICK"                   :name = "Brick";
                                                 break;
            case "COAL"                         :name = "Coal";
                                                 break;
            case "COAL_BLOCK"                   :name = "Coal Block";
                                                 break;
            case "COAL_ORE"                     :name = "Coal Ore";
                                                 break;
            case "COBBLE_WALL"                  :if(i.getData().getData() == 1) name = "Mossy Cobblestone Wall"; else name = "Cobblestone Wall";
                                                 break;
            case "COBBLESTONE"                  :name = "Cobblestone";
                                                 break;
            case "COBBLESTONE_STAIRS"           :name = "Cobblestone Stairs";
                                                 break;
            case "COMPASS"                      :name = "Compass";
                                                 break;
            case "CONCRETE"                     :name = color(i.getData().getData()) + " Concrete";
                                                 break;
            case "CONCRETE_POWDER"              :name = color(i.getData().getData()) + " Concrete Powder";
                                                 break;
            case "COOKED_BEEF"                  :name = "Steak";
                                                 break;
            case "COOKED_CHICKEN"               :name = "Cooked Chicken";
                                                 break;
            case "COOKED_FISH"                  :if(i.getData().getData() == 1) name = "Cooked Salmon"; else name = "Cooked Fish";
                                                 break;
            case "COOKED_MUTTON"                :name = "Cooked Mutton";
                                                 break;
            case "COOKED_RABBIT"                :name = "Cooked Rabbit";
                                                 break;
            case "COOKIE"                       :name = "Cookie";
                                                 break;
            case "CYAN_GLAZED_TERRACOTTA"       :name = "Cyan Glazed Terracotta";
                                                 break;
            case "CYAN_SHULKER_BOX"             :name = "Cyan Shulker Box";
                                                 break;
            case "DARK_OAK_DOOR_ITEM"           :name = "Dark Oak Door";
                                                 break;
            case "DARK_OAK_FENCE"               :name = "Dark Oak Fence";
                                                 break;
            case "DARK_OAK_FENCE_GATE"          :name = "Dark Oak Fence Gate";
                                                 break;
            case "DARK_OAK_STAIRS"              :name = "Dark Oak Stairs";
                                                 break;
            case "DAYLIGHT_DETECTOR"            :name = "Daylight Sensor";
                                                 break;
            case "DEAD_BUSH"                    :name = "Dead Bush";
                                                 break;
            case "DETECTOR_RAIL"                :name = "Detector Rail";
                                                 break;
            case "DIAMOND"                      :name = "Diamond";
                                                 break;
            case "DIAMOND_AXE"                  :name = "Diamond Axe";
                                                 break;
            case "DIAMOND_BARDING"              :name = "Diamond Horse Armor";
                                                 break;                                                                 //Horse Armor
            case "DIAMOND_BLOCK"                :name = "Diamond Block";
                                                 break;
            case "DIAMOND_BOOTS"                :name = "Diamond Boots";
                                                 break;
            case "DIAMOND_CHESTPLATE"           :name = "Diamond Chestplate";
                                                 break;
            case "DIAMOND_HELMET"               :name = "Diamond Helmet";
                                                 break;
            case "DIAMOND_HOE"                  :name = "Diamond Hoe";
                                                 break;
            case "DIAMOND_LEGGINGS"             :name = "Diamond Leggings";
                                                 break;
            case "DIAMOND_ORE"                  :name = "Diamond Ore";
                                                 break;
            case "DIAMOND_PICKAXE"              :name = "Diamond Pickaxe";
                                                 break;
            case "DIAMOND_SPADE"                :name = "Diamond Shovel";
                                                 break;
            case "DIAMOND_SWORD"                :name = "Diamond Sword";
                                                 break;
            case "DIODE"                        :name = "Redstone Repeater";
                                                 break;                                                                 //Repeater
            case "DIRT"                         :if(i.getData().getData() == 2) name = "Podzol"; else if(i.getData().getData() == 1) name = "Coarse Dirt"; else name = "Dirt";
                                                 break;
            case "DISPENSER"                    :name = "Dispenser";
                                                 break;
            case "DOUBLE_PLANT"                 :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Sunflower";
                                                            break;
                                                     case 1:name = "Lilac";
                                                            break;
                                                     case 2:name = "Double tallgrass";
                                                            break;
                                                     case 3:name = "Large Fern";
                                                            break;
                                                     case 4:name = "Rose Bush";
                                                            break;
                                                     case 5:name = "Peony";
                                                            break;
                                                 }
                                                 break;
            case "DRAGON_EGG"                   :name = "Dragon Egg";
                                                 break;
            case "DRAGONS_BREATH"               :name = "Dragon's Breath";
                                                 break;
            case "DROPPER"                      :name = "Dropper";
                                                 break;
            case "EGG"                          :name = "Egg";
                                                 break;
            case "ELYTRA"                       :name = "Elytra";
                                                 break;
            case "EMERALD"                      :name = "Emerald";
                                                 break;
            case "EMERALD_BLOCK"                :name = "Emerald Block";
                                                 break;
            case "EMERALD_ORE"                  :name = "Emerald Ore";
                                                 break;
            case "EMPTY_MAP"                    :name = "Empty Map";
                                                 break;
            case "ENCHANTED_BOOK"               :name = "Enchanted Book";
                                                 break;
            case "ENCHANTMENT_TABLE"            :name = "Enchantment Table";
                                                 break;
            case "END_BRICKS"                   :name = "End Stone Bricks";
                                                 break;
            case "END_CRYSTAL"                  :name = "End Crystal";
                                                 break;
            case "END_ROD"                      :name = "End Rod";
                                                 break;
            case "ENDER_CHEST"                  :name = "Ender Chest";
                                                 break;
            case "ENDER_PEARL"                  :name = "Ender Pearl";
                                                 break;
            case "ENDER_PORTAL_FRAME"           :name = "End Portal";
                                                 break;
            case "ENDER_STONE"                  :name = "End Stone";
                                                 break;
            case "EXP_BOTTLE"                   :name = "Bottle o' Enchanting";
                                                 break;
            case "EXPLOSIVE_MINECART"           :name = "Minecardt with TNT";
                                                 break;
            case "EYE_OF_ENDER"                 :name = "Eye of Ender";
                                                 break;
            case "FEATHER"                      :name = "Feather";
                                                 break;
            case "FENCE"                        :name = "Oak Fence";
                                                 break;
            case "FENCE_GATE"                   :name = "Oak Fence Gate";
                                                 break;
            case "FERMENTED_SPIDER_EYE"         :name = "Fermented Spider Eye";
                                                 break;
            case "FIRE"                         :name = "Fire";
                                                 break;
            case "FIREBALL"                     :name = "Fire Charge";
                                                 break;
            case "FIREWORK"                     :name = "Firework Rocket";
                                                 break;
            case "FIREWORK_CHARGE"              :name = "Firework Star";
                                                 break;
            case "FISHING_ROD"                  :name = "Fishing Rod";
                                                 break;
            case "FLINT"                        :name = "Flint";
                                                 break;
            case "FLINT_AND_STEEL"              :name = "Flint and Steel";
                                                 break;
            case "FLOWER_POT_ITEM"              :name = "Flower Pot";
                                                 break;
            case "FURNACE"                      :name = "Furnace";
                                                 break;
            case "GHAST_TEAR"                   :name = "Ghast Tear";
                                                 break;
            case "GLASS"                        :name = "Glass";
                                                 break;
            case "GLASS_BOTTLE"                 :name = "Glass Bottle";
                                                 break;
            case "GLOWSTONE"                    :name = "Glowstone";
                                                 break;
            case "GLOWSTONE_DUST"               :name = "Glowstone Dust";
                                                 break;
            case "GOLD_AXE"                     :name = "Golden Axe";
                                                 break;
            case "GOLD_BARDING"                 :name = "Golden Horse Armor";
                                                 break;
            case "GOLD_BLOCK"                   :name = "Gold Block";
                                                 break;
            case "GOLD_BOOTS"                   :name = "Golden Boots";
                                                 break;
            case "GOLD_CHESTPLATE"              :name = "Golden Chestplate";
                                                 break;
            case "GOLD_HELMET"                  :name = "Golden Helmet";
                                                 break;
            case "GOLD_HOE"                     :name = "Golden Hoe";
                                                 break;
            case "GOLD_INGOT"                   :name = "Gold Ingot";
                                                 break;
            case "GOLD_LEGGINGS"                :name = "Golden Leggings";
                                                 break;
            case "GOLD_NUGGET"                  :name = "Gold Nugget";
                                                 break;
            case "GOLD_ORE"                     :name = "Gold Ore";
                                                 break;
            case "GOLD_PICKAXE"                 :name = "Golden Pickaxe";
                                                 break;
            case "GOLD_PLATE"                   :name = "Weighted Pressure Plate (Light)";
                                                 break;
            case "GOLD_RECORD"                  :name = "Music Disc";
                                                 break;                                                                 //Music Disc
            case "GOLD_SPADE"                   :name = "Golden Shovel";
                                                 break;
            case "GOLD_SWORD"                   :name = "Golden Sword";
                                                 break;
            case "GOLDEN_APPLE"                 :name = "Golden Apple";
                                                 break;
            case "GOLDEN_CARROT"                :name = "Golden Carrot";
                                                 break;
            case "GRASS"                        :name = "Grass Block";
                                                 break;
            case "GRASS_PATH"                   :name = "Grass Path";
                                                 break;
            case "GRAVEL"                       :name = "Gravel";
                                                 break;
            case "GRAY_GLAZED_TERRACOTTA"       :name = "Gray Glazed Terracotta";
                                                 break;
            case "GRAY_SHULKER_BOX"             :name = "Gray Shulker Box";
                                                 break;
            case "GREEN_GLAZED_TERRACOTTA"      :name = "Green Glazed Terracotta";
                                                 break;
            case "GREEN_RECORD"                 :name = "Music Disc";
                                                 break;
            case "GREEN_SHULKER_BOX"            :name = "Green Shulker Box";
                                                 break;
            case "GRILLED_PORK"                 :name = "Cooked Porkchop";
                                                 break;
            case "HARD_CLAY"                    :name = "Terracotta";
                                                 break;
            case "HAY_BLOCK"                    :name = "Hay Bale";
                                                 break;
            case "HOPPER"                       :name = "Hopper";
                                                 break;
            case "HOPPER_MINECRAFT"             :name = "Minecarft with Hopper";
                                                 break;
            case "HUGE_MUSHROOM_1"              :name = "Mushroom";
                                                 break;
            case "HUGE_MUSHROOM_2"              :name = "Mushroom";
                                                 break;
            case "ICE"                          :name = "Ice";
                                                 break;
            case "INK_SACK"                     :name = "Ink Sack";
                                                 break;
            case "IRON_AXE"                     :name = "Iron Axe";
                                                 break;
            case "IRON_BARDING"                 :name = "Iron Horse Armor";
                                                 break;
            case "IRON_BLOCK"                   :name = "Iron Block";
                                                 break;
            case "IRON_BOOTS"                   :name = "Iron Boots";
                                                 break;
            case "IRON_CHESTPLATE"              :name = "Iron Chestplate";
                                                 break;
            case "IRON_DOOR"                    :name = "Iron Door";
                                                 break;
            case "IRON_FENCE"                   :name = "Iron Bars";
                                                 break;                                                                 //Iron Bars
            case "IRON_HELMET"                  :name = "Iron Helmet";
                                                 break;
            case "IRON_HOE"                     :name = "Iron Hoe";
                                                 break;
            case "IRON_INGOT"                   :name = "Iron Ingot";
                                                 break;
            case "IRON_LEGGINGS"                :name = "Iron Leggings";
                                                 break;
            case "IRON_NUGGET"                  :name = "Iron Nugget";
                                                 break;
            case "IRON_ORE"                     :name = "Iron Ore";
                                                 break;
            case "IRON_PICKAXE"                 :name = "Iron Pickaxe";
                                                 break;
            case "IRON_PLATE"                   :name = "Weighted Pressure Plate (Heavy)";
                                                 break;
            case "IRON_SPADE"                   :name = "Iron Shovel";
                                                 break;
            case "IRON_SWORD"                   :name = "Iron Sword";
                                                 break;
            case "IRON_TRAPDOOR"                :name = "Iron Trapdoor";
                                                 break;
            case "ITEM_FRAME"                   :name = "Item Frame";
                                                 break;
            case "JACK_O_LANTERN"               :name = "Jack o'Lantern";
                                                 break;
            case "JUKEBOX"                      :name = "Jukebox";
                                                 break;
            case "JUNGLE_DOOR_ITEM"             :name = "Jungle Door";
                                                 break;
            case "JUNGLE_FENCE"                 :name = "Jungle Fence";
                                                 break;
            case "JUNGLE_FENCE_GATE"            :name = "Jungle Fence Gate";
                                                 break;
            case "JUNGLE_WOOD_STAIRS"           :name = "Jungle Wood Stairs";
                                                 break;
            case "KNOWLEDGE_BOOK"               :name = "Knowledge Book";
                                                 break;
            case "LADDER"                       :name = "Ladder";
                                                 break;
            case "LAPIS_BLOCK"                  :name = "Lapis Lazuli Block";
                                                 break;
            case "LAPIS_ORE"                    :name = "Lapis Lazuli Ore";
                                                 break;
            case "LAVA"                         :name = "Flowing Lava";
                                                 break;
            case "LAVA_BUCKET"                  :name = "Lava Bucket";
                                                 break;
            case "LEASH"                        :name = "Leash";
                                                 break;
            case "LEATHER"                      :name = "Leather";
                                                 break;
            case "LEATHER_BOOTS"                :name = "Leather Boots";
                                                 break;
            case "LEATHER_CHESTPLATE"           :name = "Leather Chestplate";
                                                 break;
            case "LEATHER_HELMET"               :name = "Leather Helmet";
                                                 break;
            case "LEATHER_LEGGINGS"             :name = "Leather Leggings";
                                                 break;
            case "LEAVES"                       :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Oak Leaves";
                                                            break;
                                                     case 1:name = "Spruce Leaves";
                                                            break;
                                                     case 2:name = "Birch Leaves";
                                                            break;
                                                     case 3:name = "Jungle Leaves";
                                                            break;
                                                 }
                                                 break;
            case "LEAVES_2"                     :if(i.getData().getData() == 1) name = "Dark Oak Leaves"; else name = "Acacia Leaves";
                                                 break;
            case "LEVER"                        :name = "Lever";
                                                 break;
            case "LIGHT_BLUE_GLAZED_TERRACOTTA" :name = "Light Blue Glazed Terracotta";
                                                 break;
            case "LIGHT_BLUE_SHULKER_BOX"       :name = "Light Blue Shulker Box";
                                                 break;
            case "LIME_GLAZED_TERRACOTTA"       :name = "Lime Glazed Terracotta";
                                                 break;
            case "LIME_SHULKER_BOX"             :name = "Lime Shulker Box";
                                                 break;
            case "LINGERING_POTION"             :name = "Lingering Potion" + potion(i);
                                                 break;
            case "LOG"                          :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Oak Wood";
                                                         break;
                                                     case 1:name = "Spruce Wood";
                                                         break;
                                                     case 2:name = "Birch Wood";
                                                         break;
                                                     case 3:name = "Jungle Wood";
                                                         break;
                                                 }
                                                 break;
            case "LOG_2"                        :if(i.getData().getData() == 1) name = "Dark Oak Wood"; else name = "Acacia Wood";
                                                 break;
            case "LONG_GRASS"                   :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Shrub";
                                                         break;
                                                     case 1:name = "Grass";
                                                         break;
                                                     case 2:name = "Fern";
                                                         break;
                                                 }
                                                 break;
            case "MAGENTA_GLAZED_TERRACOTTA"    :name = "Magenta Glazed Terracotta";
                                                 break;
            case "MAGENTA_SHULKER_BOX"          :name = "Magenta Shulker Box";
                                                 break;
            case "MAGMA"                        :name = "Magma Block";
                                                 break;
            case "MAGMA_CREAM"                  :name = "Magma Cream";
                                                 break;
            case "MAP"                          :name = "Map";
                                                 break;
            case "MELON"                        :name = "Melon";
                                                 break;
            case "MELON_BLOCK"                  :name = "Melon";
                                                 break;
            case "MELON_SEEDS"                  :name = "Melon Seeds";
                                                 break;
            case "MILK_BUCKET"                  :name = "Milk";
                                                 break;
            case "MINECART"                     :name = "Minecart";
                                                 break;
            case "MOB_SPAWNER"                  :name = "Monster Spawner";
                                                 break;
            case "MONSTER_EGG"                  :switch(((SpawnEggMeta) i.getItemMeta()).getSpawnedType().getName().toUpperCase())
                                                 {
                                                     case "BAT"             :name = "Spawn Bat";
                                                                             break;
                                                     case "BLAZE"           :name = "Spawn Blaze";
                                                                             break;
                                                     case "CAVE_SPIDER"     :name = "Spawn Cave Spider";
                                                                             break;
                                                     case "CHICKEN"         :name = "Spawn Chicken";
                                                                             break;
                                                     case "COW"             :name = "Spawn Cow";
                                                                             break;
                                                     case "CREEPER"         :name = "Spawn Creeper";
                                                                             break;
                                                     case "DONKEY"          :name = "Spawn Donkey";
                                                                             break;
                                                     case "ELDER_GUARDIAN"  :name = "Spawn Elder Guardian";
                                                                             break;
                                                     case "ENDERMAN"        :name = "Spawn Enderman";
                                                                             break;
                                                     case "ENDERMITE"       :name = "Spawn Endermite";
                                                                             break;
                                                     case "EVOKER"          :name = "Spawn Evoker";
                                                                             break;
                                                     case "GHAST"           :name = "Spawn Ghast";
                                                                             break;
                                                     case "GUARDIAN"        :name = "Spawn Guardian";
                                                                             break;
                                                     case "HORSE"           :name = "Spawn Horse";
                                                                             break;
                                                     case "HUSK"            :name = "Spawn Husk";
                                                                             break;
                                                     case "LLAMA"           :name = "Spawn Llama";
                                                                             break;
                                                     case "MAGMA_CUBE"      :name = "Spawn Magma Cube";
                                                                             break;
                                                     case "MOOSHROOM"       :name = "Spawn Mooshroom";
                                                                             break;
                                                     case "MULE"            :name = "Spawn Mule";
                                                                             break;
                                                     case "OCELOT"          :name = "Spawn Ocelot";
                                                                             break;
                                                     case "PARROT"          :name = "Spawn Parrot";
                                                                             break;
                                                     case "PIG"             :name = "Spawn Pig";
                                                                             break;
                                                     case "POLAR_BEAR"      :name = "Spawn Polar Bear";
                                                                             break;
                                                     case "RABBIT"          :name = "Spawn Rabbit";
                                                                             break;
                                                     case "SHEEP"           :name = "Spawn Sheep";
                                                                             break;
                                                     case "SHULKER"         :name = "Spawn Shulker";
                                                                             break;
                                                     case "SILVERFISH"      :name = "Spawn Silverfish";
                                                                             break;
                                                     case "SKELETON"        :name = "Spawn Skeleton";
                                                                             break;
                                                     case "SKELETON_HORSE"  :name = "Spawn Skeleton Horse";
                                                                             break;
                                                     case "SLIME"           :name = "Spawn Slime";
                                                                             break;
                                                     case "SPIDER"          :name = "Spawn Spider";
                                                                             break;
                                                     case "SQUID"           :name = "Spawn Squid";
                                                                             break;
                                                     case "STRAY"           :name = "Spawn Stray";
                                                                             break;
                                                     case "VEX"             :name = "Spawn Vex";
                                                                             break;
                                                     case "VILLAGER"        :name = "Spawn Villager";
                                                                             break;
                                                     case "VINDICATOR"      :name = "Spawn Vindicator";
                                                                             break;
                                                     case "WITCH"           :name = "Spawn Witch";
                                                                             break;
                                                     case "WITHER_SKELETON" :name = "Spawn Wither Skeleton";
                                                                             break;
                                                     case "WOLF"            :name = "Spawn Wolf";
                                                                             break;
                                                     case "ZOMBIE"          :name = "Spawn Zombie";
                                                                             break;
                                                     case "ZOMBIE_HORSE"    :name = "Spawn Zombie Horse";
                                                                             break;
                                                     case "ZOMBIE_PIGMAN"   :name = "Spawn Zombie Pigman";
                                                                             break;
                                                     case "ZOMBIE_VILLAGER" :name = "Spawn Zombie Villager";
                                                                             break;
                                                 }
                                                 break;                                                                 //Spawn Egg
            case "MONSTER_EGGS"                 :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Stone Monster Egg";
                                                            break;
                                                     case 1:name = "Cobblestone Monster Egg";
                                                            break;
                                                     case 2:name = "Stone Brick Monster Egg";
                                                            break;
                                                     case 3:name = "Mossy Stone Brick Monster Egg";
                                                            break;
                                                     case 4:name = "Cracked Stone Brick Monster Egg";
                                                            break;
                                                     case 5:name = "Chiseled Stone Brick Monster Egg";
                                                            break;
                                                 }
                                                 break;                                                                 //Spawn Block (Hidden Silverfish)
            case "MOSSY_COBBLESTONE"            :name = "Moss Stone";
                                                 break;
            case "MUSHROOM_SOUP"                :name = "Mushroom Stew";
                                                 break;
            case "MUTTON"                       :name = "Raw Mutton";
                                                 break;
            case "MYCEL"                        :name = "Mycelium";
                                                 break;
            case "NAME_TAG"                     :name = "Name Tag";
                                                 break;
            case "NETHER_BRICK"                 :name = "Nether Brick";
                                                 break;
            case "NETHER_BRICK_ITEM"            :name = "Nether Brick";
                                                 break;
            case "NETHER_BRICK_STAIRS"          :name = "Nether Brick Stairs";
                                                 break;
            case "NETHER_FENCE"                 :name = "Nether Brick Fence";
                                                 break;
            case "NETHER_WARTS"                 :name = "Nether Wart";
                                                 break;
            case "NETHERRACK"                   :name = "Netherrack";
                                                 break;
            case "NOTE_BLOCK"                   :name = "Note Block";
                                                 break;
            case "OBSERVER"                     :name = "Observer";
                                                 break;
            case "OBSIDIAN"                     :name = "Obsidian";
                                                 break;
            case "ORANGE_GLAZED_TERRACOTTA"     :name = "Orange Glazed Terracotta";
                                                 break;
            case "ORANGE_SHULKER_BOX"           :name = "Orange Shulker Box";
                                                 break;
            case "PACKED_ICE"                   :name = "Packed Ice";
                                                 break;
            case "PAINTING"                     :name = "Painting";
                                                 break;
            case "PAPER"                        :name = "Paper";
                                                 break;
            case "PINK_GLAZED_TERRACOTTA"       :name = "Pink Glazed Terracotta";
                                                 break;
            case "PINK_SHULKER_BOX"             :name = "Pink Shulker Box";
                                                 break;
            case "PISTON_BASE"                  :name = "Piston";
                                                 break;
            case "PISTON_STICKY_BASE"           :name = "Sticky Piston";
                                                 break;
            case "POISONOUS_POTATO"             :name = "Poisonous Potato";
                                                 break;
            case "PORK"                         :name = "Raw Porkchop";
                                                 break;
            case "POTATO_ITEM"                  :name = "Raw Potato";
                                                 break;
            case "POTION"                       :name = "Potion" + potion(i);
                                                 break;
            case "POWERED_MINECART"             :name = "Minecart with Furnace";
                                                 break;
            case "POWERED_RAIL"                 :name = "Powered Rail";
                                                 break;
            case "PRISMARINE"                   :if(i.getData().getData() == 2) name = "Dark Prismarine"; else if(i.getData().getData() == 1) name = "Prismarine Bricks"; else name = "Prismarine";
                                                 break;
            case "PRISMARINE_CRYSTALS"          :name = "Prismarine Crystals";
                                                 break;
            case "PRISMARINE_SHARD"             :name = "Prismarine Shard";
                                                 break;
            case "PUMPKIN"                      :name = "Pumpkin";
                                                 break;
            case "PUMPKIN_PIE"                  :name = "Pumpkin Pie";
                                                 break;
            case "PUMPKIN_SEEDS"                :name = "Pumpkin Seeds";
                                                 break;
            case "PURPLE_GLAZED_TERRACOTTA"     :name = "Purple Glazed Terracotta";
                                                 break;
            case "PURPLE_SHULKER_BOX"           :name = "Purple Shulker Box";
                                                 break;
            case "PURPUR_BLOCK"                 :name = "Purpur Block";
                                                 break;
            case "PURPUR_PILLAR"                :name = "Purpur Pillar";
                                                 break;
            case "PURPUR_SLAB"                  :name = "Purpur Slab";
                                                 break;
            case "PURPUR_STAIRS"                :name = "Purpur Stairs";
                                                 break;
            case "QUARTZ"                       :name = "Nether Quartz";
                                                 break;
            case "QUARTZ_BLOCK"                 :name = "Block of Quartz";
                                                 break;
            case "QUARTZ_ORE"                   :name = "Nether Quartz Ore";
                                                 break;
            case "QUARTZ_STAIRS"                :name = "Quartz Stairs";
                                                 break;
            case "RABBIT"                       :name = "Raw Rabbit";
                                                 break;
            case "RABBIT_FOOT"                  :name = "Rabbit's Foot";
                                                 break;
            case "RABBIT_HIDE"                  :name = "Rabbit Hide";
                                                 break;
            case "RABBIT_STEW"                  :name = "Rabbit Stew";
                                                 break;
            case "RAILS"                        :name = "Rail";
                                                 break;
            case "RAW_BEEF"                     :name = "Raw Beef";
                                                 break;
            case "RAW_CHICKEN"                  :name = "Raw Chicken";
                                                 break;
            case "RAW_FISH"                     :name = "Raw Fish";
                                                 break;
            case "RECORD_3"                     :name = "Music Disc";
                                                 break;
            case "RECORD_4"                     :name = "Music Disc";
                                                 break;
            case "RECORD_5"                     :name = "Music Disc";
                                                 break;
            case "RECORD_6"                     :name = "Music Disc";
                                                 break;
            case "RECORD_7"                     :name = "Music Disc";
                                                 break;
            case "RECORD_8"                     :name = "Music Disc";
                                                 break;
            case "RECORD_9"                     :name = "Music Disc";
                                                 break;
            case "RECORD_10"                    :name = "Music Disc";
                                                 break;
            case "RECORD_11"                    :name = "Music Disc";
                                                 break;
            case "RECORD_12"                    :name = "Music Disc";
                                                 break;
            case "RED_GLAZED_TERRACOTTA"        :name = "Red Glazed Terracotta";
                                                 break;
            case "RED_MUSHROOM"                 :name = "Mushroom";
                                                 break;
            case "RED_NETHER_BRICK"             :name = "Red Nether Brick";
                                                 break;
            case "RED_ROSE"                     :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Poppy";
                                                            break;
                                                     case 1:name = "Blue Orchid";
                                                            break;
                                                     case 2:name = "Allium";
                                                            break;
                                                     case 3:name = "Azure Bluet";
                                                            break;
                                                     case 4:name = "Red Tulip";
                                                            break;
                                                     case 5:name = "Orange Tulip";
                                                            break;
                                                     case 6:name = "White Tulip";
                                                            break;
                                                     case 7:name = "Pink Tulip";
                                                            break;
                                                     case 8:name = "Oxeye Daisy";
                                                            break;
                                                 }
                                                 break;
            case "RED_SANDSTONE"                :if(i.getData().getData() == 2) name = "Smooth Red Sandstone"; else if(i.getData().getData() == 1) name = "Chiseled Red Sandstone"; else name = "Red Sandstone";
                                                 break;
            case "RED_SANDSTONE_STAIRS"         :name = "Red Sandstone Stairs";
                                                 break;
            case "RED_SHULKER_BOX"              :name = "Red Shulker Box";
                                                 break;
            case "REDSTONE"                     :name = "Redstone";
                                                 break;
            case "REDSTONE_BLOCK"               :name = "Block of Redstone";
                                                 break;
            case "REDSTONE_COMPARATOR"          :name = "Redstone Comparator";
                                                 break;
            case "REDSTONE_LAMP_OFF"            :name = "Redstone Lamp";
                                                 break;
            case "REDSTONE_ORE"                 :name = "Redstone Ore";
                                                 break;
            case "REDSTONE_TORCH_ON"            :name = "Redstone Torch";
                                                 break;
            case "ROTTEN_FLESH"                 :name = "Rotten Flesh";
                                                 break;
            case "SADDLE"                       :name = "Saddle";
                                                 break;
            case "SAND"                         :name = "Sand";
                                                 break;
            case "SANDSTONE"                    :if(i.getData().getData() == 2) name = "Smooth Sandstone"; else if(i.getData().getData() == 1) name = "Chiseled Sandstone"; else name = "Sandstone";
                                                 break;
            case "SANDSTONE_STAIRS"             :name = "Sandstone Stairs";
                                                 break;
            case "SAPLING"                      :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Oak Sapling";
                                                            break;
                                                     case 1:name = "Spruce Sapling";
                                                            break;
                                                     case 2:name = "Birch Sapling";
                                                            break;
                                                     case 3:name = "Jungle Sapling";
                                                            break;
                                                     case 4:name = "Acacia Sapling";
                                                            break;
                                                     case 5:name = "Dark Oak Sapling";
                                                            break;
                                                 }
                                                 break;
            case "SEA_LANTERN"                  :name = "Sea Lantern";
                                                 break;
            case "SEEDS"                        :name = "Seeds";
                                                 break;
            case "SHEARS"                       :name = "Shears";
                                                 break;
            case "SHIELD"                       :name = "Shield";
                                                 break;
            case "SHULKER_SHELL"                :name = "Shulker Shell";
                                                 break;
            case "SIGN"                         :name = "Sign";
                                                 break;
            case "SILVER_GLAZED_TERRACOTTA"     :name = "Light Gray Glazed Terracotta";
                                                 break;
            case "SILVER_SHULKER_BOX"           :name = "Light Gray Shulker Box";
                                                 break;
            case "SKULL_ITEM"                   :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Skeleton Skull";
                                                            break;
                                                     case 1:name = "Wither Skeleton Skull";
                                                            break;
                                                     case 2:name = "Zombie Head";
                                                            break;
                                                     case 3:name = "Head";
                                                            break;
                                                     case 4:name = "Creeper Head";
                                                            break;
                                                     case 5:name = "Dragon Head";
                                                            break;
                                                 }
                                                 break;
            case "SLIME_BALL"                   :name = "Slimeball";
                                                 break;
            case "SLIME_BLOCK"                  :name = "Slime Block";
                                                 break;
            case "SMOOTH_BRICK"                 :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Stone Brick";
                                                         break;
                                                     case 1:name = "Mossy Stone Brick";
                                                         break;
                                                     case 2:name = "Cracked Stone Brick";
                                                         break;
                                                     case 3:name = "Chiseled Stone Brick";
                                                         break;
                                                 }
                                                 break;
            case "SMOOTH_STAIRS"                :name = "Stone Brick Stairs";
                                                 break;
            case "SNOW_BALL"                    :name = "Snowball";
                                                 break;
            case "SNOW_BLOCK"                   :name = "Snow";
                                                 break;
            case "SOIL"                         :name = "Farmland";
                                                 break;
            case "SOUL_SAND"                    :name = "Soul Sand";
                                                 break;
            case "SPECKLED_MELON"               :name = "Glistering Melon";
                                                 break;
            case "SPECTRAL_ARROW"               :name = "Spectral Arrow";
                                                 break;
            case "SPIDER_EYE"                   :name = "Spider Eye";
                                                 break;
            case "SPLASH_POTION"                :name = "Splash Potion" + potion(i);
                                                 break;
            case "SPONGE"                       :if(i.getData().getData() == 1) name = "Wet Sponge"; else name = "Sponge";
                                                 break;
            case "SPRUCE_DOOR_ITEM"             :name = "Spruce Door";
                                                 break;
            case "SPRUCE_FENCE"                 :name = "Spruce Fence";
                                                 break;
            case "SPRUCE_FENCE_GATE"            :name = "Spruce Fence Gate";
                                                 break;
            case "SPRUCE_WOOD_STAIRS"           :name = "Spruce Wood Stairs";
                                                 break;
            case "STAINED_CLAY"                 :name = color(i.getData().getData()) + " Terracotta";
                                                 break;
            case "STAINED_GLASS"                :name = color(i.getData().getData()) + " Stained Glass";
                                                 break;
            case "STAINED_GLASS_PANE"           :name = color(i.getData().getData()) + " Stained Glass Pane";
                                                 break;
            case "STATIONARY_LAVA"              :name = "Stationary Lava";
                                                 break;
            case "STATIONARY_WATER"             :name = "Stationary Water";
                                                 break;
            case "STEP"                         :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Stone Slab";
                                                            break;
                                                     case 1:name = "Sandstone Slab";
                                                            break;
                                                     case 2:name = "Wooden Slab";
                                                            break;
                                                     case 3:name = "Cobblestone Slab";
                                                            break;
                                                     case 4:name = "Bricks Slab";
                                                            break;
                                                     case 5:name = "Stone Bricks Slab";
                                                            break;
                                                     case 6:name = "Nether Brick Slab";
                                                            break;
                                                     case 7:name = "Quartz Slab";
                                                            break;
                                                 }
                                                 break;
            case "STICK"                        :name = "Stick";
                                                 break;
            case "STONE"                        :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Stone";
                                                            break;
                                                     case 1:name = "Granite";
                                                            break;
                                                     case 2:name = "Polished Granite";
                                                            break;
                                                     case 3:name = "Diorite";
                                                            break;
                                                     case 4:name = "Polished Diorite";
                                                            break;
                                                     case 5:name = "Andesite";
                                                            break;
                                                     case 6:name = "Polished Andesite";
                                                            break;
                                                 }
                                                 break;
            case "STONE_AXE"                    :name = "Stone Axe";
                                                 break;
            case "STONE_BUTTON"                 :name = "Button";
                                                 break;
            case "STONE_HOE"                    :name = "Stone Hoe";
                                                 break;
            case "STONE_PICKAXE"                :name = "Stone Pickaxe";
                                                 break;
            case "STONE_PLATE"                  :name = "Stone Pressure Plate";
                                                 break;
            case "STONE_SLAB2"                  :name = "Red Sandstone Slab";
                                                 break;
            case "STONE_SPADE"                  :name = "Stone Shovel";
                                                 break;
            case "STONE_SWORD"                  :name = "Stone Sword";
                                                 break;
            case "STORAGE_MINECART"             :name = "Minecart with Chest";
                                                 break;
            case "STRING"                       :name = "String";
                                                 break;
            case "STRUCTURE_BLOCK"              :name = "Structure Block";
                                                 break;
            case "STRUCTURE_VOID"               :name = "Structure Void";
                                                 break;
            case "SUGAR"                        :name = "Sugar";
                                                 break;
            case "SUGAR_CANE"                   :name = "Sugar Cane";
                                                 break;
            case "SULPHUR"                      :name = "Gunpowder";
                                                 break;                                                                 //Gunpowder
            case "THIN_GLASS"                   :name = "Glass Pane";
                                                 break;
            case "TIPPED_ARROW"                 :name = "Arrow" + potion(i);
                                                 break;
            case "TNT"                          :name = "TNT";
                                                 break;
            case "TORCH"                        :name = "Torch";
                                                 break;
            case "TOTEM"                        :name = "Totem of Undying";
                                                 break;
            case "TRAP_DOOR"                    :name = "Wooden Trapdoor";
                                                 break;
            case "TRAPPED_CHEST"                :name = "Trapped Chest";
                                                 break;
            case "TRIPWIRE_HOOK"                :name = "Tripwire Hook";
                                                 break;
            case "VINE"                         :name = "Vine";
                                                 break;
            case "WATCH"                        :name = "Clock";
                                                 break;
            case "WATER"                        :name = "Flowing Water";
                                                 break;
            case "WATER_BUCKET"                 :name = "Water Bucket";
                                                 break;
            case "WATER_LILY"                   :name = "Lily Pad";
                                                 break;
            case "WEB"                          :name = "Cobweb";
                                                 break;
            case "WHEAT"                        :name = "Wheat";
                                                 break;
            case "WHITE_GLAZED_TERRACOTTA"      :name = "White Glazed Terracotta";
                                                 break;
            case "WHITE_SHULKER_BOX"            :name = "White Shulker Box";
                                                 break;
            case "WOOD"                         :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Oak Wood Plank";
                                                            break;
                                                     case 1:name = "Spruce Wood Plank";
                                                            break;
                                                     case 2:name = "Birch Wood Plank";
                                                            break;
                                                     case 3:name = "Jungle Wood Plank";
                                                            break;
                                                     case 4:name = "Acacia Wood Plank";
                                                            break;
                                                     case 5:name = "Dark Oak Wood Plank";
                                                            break;
                                                 }
                                                 break;
            case "WOOD_AXE"                     :name = "Wooden Axe";
                                                 break;
            case "WOOD_BUTTON"                  :name = "Button";
                                                 break;
            case "WOOD_DOOR"                    :name = "Oak Door";
                                                 break;
            case "WOOD_HOE"                     :name = "Wooden Hoe";
                                                 break;
            case "WOOD_PICKAXE"                 :name = "Wooden Pickaxe";
                                                 break;
            case "WOOD_PLATE"                   :name = "Wooden Pressure Plate";
                                                 break;
            case "WOOD_SPADE"                   :name = "Wooden Shovel";
                                                 break;
            case "WOOD_STAIRS"                  :name = "Oak Wood Stairs";
                                                 break;
            case "WOOD_STEP"                    :switch(i.getData().getData())
                                                 {
                                                     case 0:name = "Oak Wood Plank Slab";
                                                            break;
                                                     case 1:name = "Spruce Wood Plank Slab";
                                                            break;
                                                     case 2:name = "Birch Wood Plank Slab";
                                                            break;
                                                     case 3:name = "Jungle Wood Plank Slab";
                                                            break;
                                                     case 4:name = "Acacia Wood Plank Slab";
                                                            break;
                                                     case 5:name = "Dark Oak Wood Plank Slab";
                                                            break;
                                                 }
                                                 break;
            case "WOOD_SWORD"                   :name = "Wooden Sword";
                                                 break;
            case "WOODEN_DOOR"                  :name = "Oak Door";
                                                 break;
            case "WOOL"                         :name = color(i.getData().getData()) + " Wool";
                                                 break;
            case "WORKBENCH"                    :name = "Crafting Table";
                                                 break;
            case "WRITTEN_BOOK"                 :name = "Written Book";
                                                 break;
            case "YELLOW_FLOWER"                :name = "Dandelion";
                                                 break;
            case "YELLOW_GLAZED_TERRACOTTA"     :name = "Yellow Glazed Terracotta";
                                                 break;
            case "YELLOW_SHULKER_BOX"           :name = "Yellow Shulker Box";
                                                 break;
            default                             :name = i.getType().toString().toLowerCase();
        }
        return name;
    }

    private static String color(int data)
    {
        switch(data)
        {
            case 0  :return "White";
            case 1  :return "Orange";
            case 2  :return "Magenta";
            case 3  :return "Light Blue";
            case 4  :return "Yellow";
            case 5  :return "Lime";
            case 6  :return "Pink";
            case 7  :return "Gray";
            case 8  :return "Light Gray";
            case 9  :return "Cyan";
            case 10 :return "Purple";
            case 11 :return "Blue";
            case 12 :return "Brown";
            case 13 :return "Green";
            case 14 :return "Red";
            case 15 :return "Black";
            default: return "";
        }
    }
    private static String potion(ItemStack i)
    {
        String effect = " of ";
        switch(( (PotionMeta) i.getItemMeta()).getBasePotionData().getType().getEffectType().getName().toUpperCase())
        {
            case "ABSORPTION"       :effect = effect + "Absorption";break;
            case "BLINDNESS"        :effect = effect + "Blindness";break;
            case "CONFUSION"        :effect = effect + "Nausea";break;
            case "DAMAGE_RESISTANCE":effect = effect + "Resistance";break;
            case "FAST_DIGGING"     :effect = effect + "Haste";break;
            case "FIRE_RESISTANCE"  :effect = effect + "Fire Resistance";break;
            case "GLOWING"          :effect = effect + "Glowing";break;
            case "HARM"             :effect = effect + "Instant Damage";break;
            case "HEAL"             :effect = effect + "Instant Health";break;
            case "HEALTH_BOOST"     :effect = effect + "Health Boost";break;
            case "HUNGER"           :effect = effect + "Hunger";break;
            case "INCREASE_DAMAGE"  :effect = effect + "Strength";break;
            case "INVISIBILITY"     :effect = effect + "Invisibility";break;
            case "JUMP"             :effect = effect + "Jump Boost";break;
            case "LEVITATION"       :effect = effect + "Levitation";break;
            case "LUCK"             :effect = effect + "Luck";break;
            case "NIGHT_VISION"     :effect = effect + "Night Vision";break;
            case "POISON"           :effect = effect + "Poison";break;
            case "REGENERATION"     :effect = effect + "Regeneration";break;
            case "SATURATION"       :effect = effect + "Saturation";break;
            case "SLOW"             :effect = effect + "Slowness";break;
            case "SLOW_DIGGING"     :effect = effect + "Mining Fatigue";break;
            case "SPEED"            :effect = effect + "Speed";break;
            case "UNLUCK"           :effect = effect + "Bad Luck";break;
            case "WATER_BREATHING"  :effect = effect + "Water Breathing";break;
            case "WEAKNESS"         :effect = effect + "Weakness";break;
            case "WITHER"           :effect = effect + "Wither";break;
        }
        return effect;
    }
}
